# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c760802af3c1648db7044b692f5743da0e04862f52cb1c708024b548a28159885f41d80aecd431b111303f00c7e67e04668e646cae618b4dcbd9cf2ae03e771

test:
  secret_key_base: 85e624aab8ccfa1c933e046577021d9d01554799eba28bcff29d2eb8dd101c418f10fc5b26e4e7be529014e4cb8f4c27c72b131ac178c0d942ac4c804fc8ead0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
